services:
  mysql:
    image: mysql:8
    container_name: franchises-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: franchises_db
      MYSQL_USER: franchise_user
      MYSQL_PASSWORD: jCR7D53n&3]z
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: franchises-api
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8081
      DB_URL: jdbc:mysql://mysql:3306/franchises_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: franchise_user
      DB_PASSWORD: jCR7D53n&3]z
    depends_on:
      mysql:
        condition: service_healthy
