# Franchises API HTTP Requests
GET http://localhost:8081

## Franchises API

### List all franchises
GET http://localhost:8081/api/franchises

### Create a new franchise
POST http://localhost:8081/api/franchises
Content-Type: application/json

{
    "name": "Franchise 1"
}

### Create a new branch in a franchise
POST http://localhost:8081/api/franchises/2/branches
Content-Type: application/json

{
    "name": "Branch 1"
}

### Get a franchise by ID
GET http://localhost:8081/api/franchises/2

### Update a franchise
PUT http://localhost:8081/api/franchises/2
Content-Type: application/json

{
    "name": "Updated Franchise 2"
}

## Branches API

### List all branches
GET http://localhost:8081/api/branches

### Get a branch by ID
GET http://localhost:8081/api/branches/2

### Update a branch
PUT http://localhost:8081/api/branches/3
Content-Type: application/json

{
    "name": "Branch updated"
}

### Create a branch product from an existing product
POST http://localhost:8081/api/branches/2/products
Content-Type: application/json

{
    "productId": 1,
    "stock": 2
}

### Update stock of a branch product
PATCH http://localhost:8081/api/branches/2/products/1/stock
Content-Type: application/json

{
    "stock": 10
}

### Delete a branch product
DELETE http://localhost:8081/api/branches/2/products/1

## Products API

### Create a new product in catalog
POST http://localhost:8081/api/products
Content-Type: application/json

{
    "name": "Product 2"
}

### Get all products
GET http://localhost:8081/api/products

### Get a product by ID
GET http://localhost:8081/api/products/2

### Update a product
PUT http://localhost:8081/api/products/2
Content-Type: application/json

{
    "name": "Product pañales"
}

### Delete a product
DELETE http://localhost:8081/api/products/1

### Get top stock product by branch for a franchise
GET http://localhost:8081/api/franchises/2/top-stock-products
