GET http://localhost:8081

## Franchises API

### List all franchises
GET http://localhost:8081/api/franchises

### Create a new franchise
POST http://localhost:8081/api/franchises
Content-Type: application/json

{
    "name": "Franchise 1"
}

### Get a franchise by ID
GET http://localhost:8081/api/franchises/2

### Update a franchise
PUT http://localhost:8081/api/franchises/2
Content-Type: application/json

{
    "name": "Updated Franchise 2"
}

### Delete a franchise
DELETE http://localhost:8081/api/franchises/1

## Branches API

### List all branches
GET http://localhost:8081/api/branches

### Create a new branch
POST http://localhost:8081/api/branches
Content-Type: application/json

{
    "name": "Branch 1",
    "franchiseId": 2
}

### Get a branch by ID
GET http://localhost:8081/api/branches/2

### Update a branch
PUT http://localhost:8081/api/branches/3
Content-Type: application/json

{
    "name": "Branch updated"
}

### Delete a branch
DELETE http://localhost:8081/api/branches/1


## Products API

### Create a new product
POST http://localhost:8081/api/products
Content-Type: application/json

{
    "name": "Product 1",
    "stock": 0,
    "branchId": 2
}

### Get a product by ID
GET http://localhost:8081/api/products/2

### Update a product
PUT http://localhost:8081/api/products/2
Content-Type: application/json

{
    "name": "Product pañales"
}

### Delete a product
DELETE http://localhost:8081/api/products/1 

### Update stock of a product
PATCH http://localhost:8081/api/products/2/stock
Content-Type: application/json

{
    "stock": 10
}